### PR TITLE
Compatibility with ghc 8.10

### PR DESCRIPTION
**Pull request by locallycompact**
Builds with 8.6.5, 8.8.3 and 8.10.

### CODE REVIEW

**Comment by Dridus** [comment]
hey, it looks like the example project needs some bounds loosened. otherwise looks good to me!

**Comment by locallycompact** [comment]
Uh seems ok for me. What are you seeing?

**Comment by Dridus** [comment]
sorry, misunderstood at first. looks like some things example depends on don't have compatible bounds.

I tried an allow-newer build and that worked, so you could do that, or make the GHC-8.8 / LTS-16 configuration the default (i.e. `stack.yaml`).

The error:

```[nix-shell:~/vital/composite]$ ~/.local/bin/stack build

Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for servant-0.17:
    base-4.14.0.0 from stack configuration does not match >=4.9 && <4.14  (latest matching version is 4.13.0.0)
needed due to myawesomeserver-0.0.2 -> servant-0.17

In the dependencies for servant-server-0.17:
    base-4.14.0.0 from stack configuration does not match >=4.9 && <4.14  (latest matching version is 4.13.0.0)
needed due to myawesomeserver-0.0.2 -> servant-server-0.17

In the dependencies for servant-swagger-1.1.8:
    Cabal-3.2.0.0 from stack configuration does not match >=1.24 && <3.1  (latest matching version is 3.0.2.0)
    base-4.14.0.0 from stack configuration does not match >=4.9.1.0 && <4.14  (latest matching version is 4.13.0.0)
    lens-4.19.2 from stack configuration does not match >=4.17 && <4.19  (latest matching version is 4.18.1)
    swagger2-2.6 from stack configuration does not match >=2.3.0.1 && <2.6  (latest matching version is 2.5)
needed due to myawesomeserver-0.0.2 -> servant-swagger-1.1.8

In the dependencies for servant-swagger-ui-0.3.4.3.23.11:
    base-4.14.0.0 from stack configuration does not match >=4.7 && <4.14  (latest matching version is 4.13.0.0)
    swagger2-2.6 from stack configuration does not match >=2.3.0.1 && <2.6  (latest matching version is 2.5)
needed due to myawesomeserver-0.0.2 -> servant-swagger-ui-0.3.4.3.23.11

In the dependencies for servant-swagger-ui-core-0.3.3:
    base-4.14.0.0 from stack configuration does not match >=4.7 && <4.14  (latest matching version is 4.13.0.0)
    swagger2-2.6 from stack configuration does not match >=2.3.0.1 && <2.6  (latest matching version is 2.5)
needed due to myawesomeserver-0.0.2 -> servant-swagger-ui-core-0.3.3

Some different approaches to resolving this:

  * Set 'allow-newer: true' in /home/ross/.stack/config.yaml to ignore all version constraints and build anyway.

  * Build requires unattainable version of base. Since base is a part of GHC, you most likely need to use a different GHC version with the matching base.

Plan construction failed.
```

**Comment by locallycompact** [comment]
I get a successful build on `912405b242e0e1e8f27c60d2631780fb5623e143` running stack test with that default stack yaml and I don't get any errors.

**Comment by Dridus** [comment]
odd. what version of stack are you running and do you have allow-newer in your global settings? does it emit any messages pertaining to allowing newer versions?

**Comment by locallycompact** [comment]
stack 2.3.1 x86_64 hpack-0.34.2 on nix (with stack --nix test). No allow-newer no messages about versions.

**Comment by Dridus** [comment]
okay, bizarre. I extra-super-cleaned my checkout and now it works, so I guess maybe something got wedged in .stack-work or something? I dunno.

**Pull request merged**
