### PR TITLE
Update lts

### PR DESCRIPTION
**Pull request by martyall**
this upgrades the lts to 11.2 and updates the tests to compile.

### CODE REVIEW

**Comment by Dridus** [comment]
hey @blinky3713 thanks! it looks like this won't compile back on lts-9 though? at least on a skim `[]` and `(cxt [])` don't seem compatible. have you tested this on the older LTS?

**Comment by martyall** [comment]
I'm not sure what you mean "tested it on an old lts"? I have run your tests and verified that they pass after these changes. I have made a demo app which uses your library (pre lts upgrade) here https://github.com/f-o-a-m/foam.token-server, would you like me to test this?

**Comment by Dridus** [comment]
primarily I'm asking if it still compiles under the older LTS. if it doesn't, we'll probably have to add some `#if`s to test which version of `template-haskell` it's compiling against

**Comment by martyall** [comment]
Yeah, i'm sure it won't work on an older lts

**Comment by martyall** [comment]
Can I ask why you aren't publishing this with version bounds on hackage?

**Comment by Dridus** [comment]
haven't spent the time to set correct version bounds yet, that's all

**Comment by martyall** [comment]
imo it makes more sense to publish a release with version bounds as a frame of reference, but I'm not sure what you're plans are.

**Comment by Dridus** [comment]
yep, and ideally we'd publish into stackage and follow those policies as well

**Comment by martyall** [comment]
Then would you be opposed to just using the `--pvp-bounds` suggested by stack and publishing those? I'm in the process of cleaning up a few other things in  this repo and would like to continue.

**Comment by Dridus** [comment]
No that sounds like a good start, which we can adapt to fit the older lts in a separate move

**Comment by Dridus** [comment]
closing this PR in favor of #19 which has backwards compatibiltiy and the version bounds

**Comment by Dridus** [comment]
@blinky3713 composite 0.5.4.0 with this change and version bounds is uploaded to hackage. let us know if you have issues with it

**Pull request closed without merging**
